spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Tokopedia
    username: postgres
    password: GERY2020
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
